# This pipeline is triggered only for pr
trigger: autorestv3

pr:
  branches:
    include:
    - autorestv3

variables:
  NodeVersion: '10.x'
  PythonVersion: '3.6'

jobs:
  - job: 'AutoRest.Python.CI'
    displayName: 'Run AutoRest CI Checks'

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'        

      - task: UsePythonVersion@0
        displayName: 'Use Python $(PythonVersion)'
        inputs:
          versionSpec: $(PythonVersion)

      - script: pip install -r requirements.txt tox
        displayName: 'Prepare Environment'

      - script: |
          npm install
          cd tests/azure
          tox -e ci
        displayName: 'Execute Tests'

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testResultsFiles: '**/*test*.xml'
          testRunTitle: '$(OSName) Python $(PythonVersion)'

      - script: |
          coverage xml -i --omit="*test*,*example*"
        displayName: 'Generate Coverage XML'
        continueOnError: true

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage'
        continueOnError: true
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(Build.SourcesDirectory)/coverage.xml'
